config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :comments

  resources :categories

  root 'homes#index'
  
  get 'homes/index'

  resources :products do
    member do
      get "test_member"
    end
    collection do 
      get "test_collection"
      get "search"
    end
  end

  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base

	belongs_to :category
	has_many :comments

	validates :name, :presence => true 
	validates :description, :presence => true 
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  before_save :add_authen_token

  def add_authen_token
  	byebug
  	#self.authen_token = params[:authenticity_token]
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout false
  skip_before_action :verify_authenticity_token
  def new
    @comment = Comment.new
  end

  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
   
      @comment = Comment.new(comment_params)
    #@comment = Comment.new(:content => params[:content] , :product_id => params[:product_id])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @posts_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

    def comment_params
      params.require(:comment).permit(:content,:product_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
   # @categories = Category.all

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @new_comment = Comment.new
    @comments = @product.comments
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  #test member
  def test_member
    puts params[:id]
  end

  def test_collection
    puts "----------------test_collection-------------------"
  end

  def search
    @key_search = params[:key_search]

  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
#begin khac rails 3
private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for (@category) do |f|
  - if @category.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@category.errors.count, "error")
          prohibited this category from being saved:
      .panel-body
        %ul
          - @category.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-5
      = f.text_field :name, :class => 'form-control'
      = f.submit nil, :class => 'btn btn-primary'
            
                     

app/views/categories/edit.html.haml
%h1 Editing category
= render 'form'
= link_to 'Show', @category
%br
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing Categories
.container
  .table-bordered
    %table.table
      %thead
        %tr
          %th Name
          %th{:colspan => "3"}
      %tbody
        - @categories.each do |category|
          %tr
            %td= category.name
            %td= link_to 'Show', category,:class => 'btn btn-warning'
            %td= link_to 'Edit',  edit_category_path(category),:class => 'btn btn-info'
            %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger'
%br/
= link_to 'New category', new_category_path,:class => 'btn btn-default'

app/views/categories/new.html.haml
%h1 New category
= render 'form'
= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p
  %strong Name:
  = @category.name
= link_to 'Edit', edit_category_path(@category)
= link_to 'Back', categories_path

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/1application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubytraining</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
	<%= link_to 'Products',products_path,:class => 'btn btn-info'%>
	<%= link_to 'Home', root_path,:class => 'btn btn-info'%>
</div>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubytraining</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rubytraining
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "shared/header"
    = render "shared/main_menu"
    = yield
    = render "shared/footer"

app/views/products/_form.html.haml
= form_for (@product), :html => {:multipart => true, :class => "form-horizontal product" } do |f|
  - if @product.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@product.errors.count, "error")
          prohibited this product from being saved:
      .panel-body
        %ul
          - @product.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-5
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :image, :class => 'control-label col-lg-2'
    .col-lg-5
      = f.file_field :image
  .form-group
    = f.label :description, :class => 'control-label col-lg-2'
    .col-lg-5
      = f.text_area :description,:rows => 3, :class => 'form-control'
  .form-group
    = f.label :category_id, :class => 'control-label col-lg-2'
    .col-lg-3
      = select(:product, :category_id, options_from_collection_for_select(@categories, :id, :name)) 
  .form-group
    = f.label :price, :class => 'control-label col-lg-2'
    .col-lg-3
      = f.text_field :price, :class => 'form-control'
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'

                     

app/views/products/edit.html.haml
%h1 Editing product
= render 'form'
= link_to 'Show', @product 
%br
= link_to 'Back', products_path, :class => 'btn btn-default'

app/views/products/index.html.haml
.row
  .container.header_top
    .table-bordered
      %table.table
        %thead
          %tr
            %th Name
            %th Description
            %th Price
            %th Image
            %th Category
            %th{:colspan => "4"}
        %tbody
          - @products.each do |product|
            %tr
              %td= product.name
              %td= product.description
              %td= product.price
              %td= product.image
              %td= product.category.name
              %td= link_to 'Show', product,:class => 'btn btn-warning'
              %td= link_to 'Edit',  edit_product_path(product),:class => 'btn btn-info'
              %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger'
  %br/
  = link_to 'New Product', new_product_path,:class => 'btn btn-default'

app/views/products/new.html.haml
%h1 New product
= render 'form'
= link_to 'Back', products_path,:class => 'btn btn-default'

app/views/products/search.html.haml
= @key_search

app/views/products/show.html.haml
%p
  %strong Name:
  = @product.name
%p
  %strong Description:
  = @product.description
%p
  %strong Price:
  = @product.price
%form{:action => comments_path, :method =>"post"}
  %textarea{:name => "comment[content]"}
  %p
  %input{:name=>"comment[product_id]", :type=>"hidden",:value => @product.id}
    %button.btn.btn-info.dropdown-toggle{:type => "submit"} Submit
    %p All comment
.commnents
  - @comments.each do |comment|
    %p
      %span= comment.id
      %span= comment.content 

= link_to 'Edit', edit_product_path(@product)
= link_to 'Back', products_path

app/views/products3/_form.html.erb
<%= form_for @product, :url => products_path, :html => {:multipart => true, :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.text_area :description,:rows => 3, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products5/_form.html.erb
<%= form_for @product, :url => products_path, :html => {:multipart => true, :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.text_area :description,:rows => 3, :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary', :onclick= "kiem_tra()" %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products5/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path :class => 'btn btn-default'%>

app/views/products5/index.html.erb
<h1>Listing products</h1>
<div class="container">
<form action=<%= search_products_path%> method="get">
     <input name="key_search" class="form-control"></input>
     <p class = "text-center"> <button type="submit" class="btn btn-info dropdown-toggle">Search
     </button>
     </p>
</form>     
 <div class="table-bordered">     
   <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Image</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.image %></td>
        <td><%= link_to 'Show', product,:class => 'btn btn-warning' %></td>
        <td><%= link_to 'Edit', edit_product_path(product),:class => 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
<br>

<%= link_to 'New Product', new_product_path,:class => 'btn btn-default' %>

app/views/products5/index.html.haml
%h1 Listing products
.container
  %form{:action => "<haml_loud"}
    search_products_path method="get">
    %input.form-control{:name => "key_search"}/
    %p.text-center
      %button.btn.btn-info.dropdown-toggle{:type => "submit"}
        Search
  .table-bordered
    %table.table
      %thead
        %tr
          %th Name
          %th Description
          %th Price
          %th Image
          %th{:colspan => "3"}
      %tbody
        - @products.each do |product|
          %tr
            %td= product.name
            %td= product.description
            %td= product.price
            %td= product.image
            %td= link_to 'Show', product,:class => 'btn btn-warning'
            %td= link_to 'Edit', edit_product_path(product),:class => 'btn btn-info'
            %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger'
%br/
= link_to 'New Product', new_product_path,:class => 'btn btn-default'

app/views/products5/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path,:class => 'btn btn-default' %>

app/views/products5/search.html.erb
<div><%= @key_search%></div>

app/views/products5/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products5/test_collection.html.erb
test_collection

app/views/products5/test_member.html.erb
hello member

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
	.container
		.col-md-3.header_top=image_tag "logo.png"
		.col-md-5.header_top
			%form{:action => search_products_path, :method =>"get", :role => "form"}
				.input-group
					%input.form-control.txtSearch{:name => "key_search", :placeholder => "Product name", :type => "text"}
						%span.input-group-btn
							%input.btn.btn-info{:type => "submit", :value => "Search"}
		#navbar.navbar-collapse.collapse.col-md-4
			%ul.nav.navbar-nav.navbar-right
				%li.active
					%a sign out
				%li
					%a Sign up
				

app/views/shared/_main_menu.html.haml
.row.main_menu_top
	.col-lg-12
		#main_menu
			= link_to 'Home', root_path
			= link_to 'Product', products_path
		